server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  #通过这两个属性表示自己是个server
    fetchRegistry: false  #通过这两个属性表示自己是个server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: cloud-server


