eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: server-zuul
zuul:
  routes:
    api-a:   #以api-a开头的请求都转发给ribbon服务
      path: /api-a/**
      serviceId: CLOUD-CONSUMER
    api-b:   #以api-b开头的请求都转发给feign服务
      path: /api-b/**
      serviceId: CONSUMER-FEGIN

