eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764

spring:
  application:
    name: consumer-fegin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

feign:
  hystrix:
    enabled: true



mybatis:
  type-aliases-package: com.spring.consumerfeign.entity
  mapper-locations: classpath:mapper/*Mapper.xml
